import assert from "node:assert/strict";
import { randomUUID } from "node:crypto";
import test from "node:test";

import pg from "pg";

import { authorizeUadAppraiserConfirmation, authorizeUadWorkfileAccess } from "../src/modules/uad/access.js";
import { applyUadCompletionSuggestions } from "../src/modules/uad/completionApply.js";
import { loadUadCompletionSuggestions } from "../src/modules/uad/completionSuggestions.js";
import { createUadWorkfile } from "../src/modules/uad/workfiles.js";
import { customAppraisalReportFixture } from "./fixtures/customAppraisalReportFixture.js";

const databaseUrl = process.env.DATABASE_URL;

async function cleanupIntegrationFixture(pool, accountId, organizationId, actorUserId) {
  const client = await pool.connect();
  try {
    await client.query("BEGIN");
    await client.query(
      `DELETE FROM app.appraisal_file_replications
        WHERE source_report_file_id IN (SELECT id FROM app.report_files WHERE account_id = $1)
           OR target_report_file_id IN (SELECT id FROM app.report_files WHERE account_id = $1)`,
      [accountId],
    );
    await client.query(
      `UPDATE app.report_files
          SET subject_snapshot_id = NULL, previous_report_file_id = NULL
        WHERE account_id = $1`,
      [accountId],
    );
    await client.query(
      `DELETE FROM app.appraisal_subject_snapshots
        WHERE appraisal_case_id IN (SELECT id FROM app.appraisal_cases WHERE account_id = $1)`,
      [accountId],
    );
    await client.query("DELETE FROM app.report_files WHERE account_id = $1", [accountId]);
    await client.query(
      `DELETE FROM app.custom_appraisal_workfile_sections
        WHERE assignment_file_id IN (SELECT id FROM app.assignment_files WHERE account_id = $1)`,
      [accountId],
    );
    await client.query(
      `DELETE FROM app.custom_appraisal_workfiles
        WHERE assignment_file_id IN (SELECT id FROM app.assignment_files WHERE account_id = $1)`,
      [accountId],
    );
    await client.query("DELETE FROM app.assignment_files WHERE account_id = $1", [accountId]);
    await client.query("DELETE FROM app.appraisal_cases WHERE account_id = $1", [accountId]);

    const workfiles = "SELECT id FROM appraisal.uad_workfiles WHERE account_id = $1";
    await client.query(`DELETE FROM appraisal.uad_audit_events WHERE workfile_id IN (${workfiles})`, [accountId]);
    await client.query(`DELETE FROM appraisal.uad_revisions WHERE workfile_id IN (${workfiles})`, [accountId]);
    await client.query(`DELETE FROM appraisal.uad_field_values WHERE workfile_id IN (${workfiles})`, [accountId]);
    await client.query(
      `DELETE FROM appraisal.uad_entities
        WHERE workfile_id IN (${workfiles}) AND parent_entity_id IS NOT NULL`,
      [accountId],
    );
    await client.query(`DELETE FROM appraisal.uad_entities WHERE workfile_id IN (${workfiles})`, [accountId]);
    await client.query(`DELETE FROM appraisal.uad_subject_snapshots WHERE workfile_id IN (${workfiles})`, [accountId]);
    await client.query("DELETE FROM appraisal.uad_workfiles WHERE account_id = $1", [accountId]);
    await client.query("DELETE FROM core.primary_improvements WHERE account_id = $1", [accountId]);
    await client.query("DELETE FROM core.accounts WHERE account_id = $1", [accountId]);
    // These identifiers are generated by this test, never shared identity rows.
    await client.query("DELETE FROM app_auth.membership_roles WHERE organization_id = $1 AND user_id = $2",
      [organizationId, actorUserId]);
    await client.query("DELETE FROM app_auth.organization_memberships WHERE organization_id = $1 AND user_id = $2",
      [organizationId, actorUserId]);
    await client.query("DELETE FROM app_auth.organizations WHERE id = $1", [organizationId]);
    await client.query("DELETE FROM app_auth.users WHERE id = $1", [actorUserId]);
    await client.query("COMMIT");
  } catch (error) {
    await client.query("ROLLBACK").catch(() => {});
    throw error;
  } finally {
    client.release();
  }
}

test("reviewed Custom Appraisal suggestions apply atomically to a real UAD database", {
  skip: !databaseUrl,
}, async () => {
  const pool = new pg.Pool({ connectionString: databaseUrl, max: 3 });
  const accountId = `C${randomUUID().replaceAll("-", "")}`;
  const organizationId = randomUUID();
  const actorUserId = randomUUID();
  try {
    await pool.query(
      `INSERT INTO app_auth.organizations (id, legal_name, display_name)
       VALUES ($1, 'Synthetic completion organization', 'Synthetic completion organization')`,
      [organizationId],
    );
    await pool.query(
      "INSERT INTO app_auth.users (id, email, display_name) VALUES ($1, $2, 'Synthetic completion appraiser')",
      [actorUserId, `${actorUserId}@example.test`],
    );
    await pool.query(
      "INSERT INTO app_auth.organization_memberships (organization_id, user_id, status) VALUES ($1, $2, 'active')",
      [organizationId, actorUserId],
    );
    await pool.query(
      "INSERT INTO app_auth.membership_roles (organization_id, user_id, role_code) VALUES ($1, $2, 'appraiser')",
      [organizationId, actorUserId],
    );
    await pool.query(
      `INSERT INTO core.accounts (
         account_id, county, address, city, postal_code, neighborhood_code,
         subdivision, legal_description
       ) VALUES ($1, 'Test County', '100 Integration Way', 'Garland', '75044',
         'TEST-1', 'Integration Addition', 'LOT 1 BLOCK A')`,
      [accountId],
    );
    await pool.query(
      `INSERT INTO core.primary_improvements (
         account_id, year_built, living_area_sqft, bedroom_count, bath_count, number_units
       ) VALUES ($1, 2001, 1800, 3, 2, 1)`,
      [accountId],
    );

    const workfile = await createUadWorkfile(pool, accountId, {
      file_number: `UAD-INT-${Date.now()}`,
      assignment_purpose: "Purchase",
      organization_id: organizationId,
      assigned_appraiser_user_id: actorUserId,
      actor_user_id: actorUserId,
    });
    const uadReport = await pool.query(
      `SELECT id, appraisal_case_id, subject_snapshot_id
         FROM app.report_files
        WHERE uad_workfile_id = $1`,
      [workfile.id],
    );
    assert.ok(uadReport.rows[0]?.appraisal_case_id);
    assert.ok(uadReport.rows[0]?.subject_snapshot_id);

    const assignment = await pool.query(
      `INSERT INTO app.assignment_files (
         account_id, file_number, assignment_details, organization_id, assigned_appraiser_user_id
       ) VALUES ($1, $2, $3::jsonb, $4, $5)
       RETURNING id`,
      [
        accountId,
        `CUSTOM-INT-${Date.now()}`,
        JSON.stringify({ assignment_types: ["purchase_transaction"] }),
        organizationId,
        actorUserId,
      ],
    );
    const assignmentId = assignment.rows[0].id;
    await pool.query(
      `INSERT INTO app.custom_appraisal_workfiles (assignment_file_id, canonical_file_name)
       VALUES ($1, $2)`,
      [assignmentId, `integration-${assignmentId}.homenode-appraisal.json`],
    );

    const customReportId = randomUUID();
    await pool.query(
      `INSERT INTO app.report_files (
         id, account_id, workflow_type, file_number, custom_assignment_file_id,
         is_current, registry_revision, appraisal_case_id, subject_snapshot_id, organization_id
       ) VALUES ($1, $2, 'custom_appraisal', $3, $4, true, 1, $5, $6, $7)`,
      [
        customReportId,
        accountId,
        `CUSTOM-INT-${assignmentId}`,
        assignmentId,
        uadReport.rows[0].appraisal_case_id,
        uadReport.rows[0].subject_snapshot_id,
        organizationId,
      ],
    );

    const fixture = customAppraisalReportFixture();
    for (const [sectionKey, section] of Object.entries(fixture.snapshot.sections)) {
      await pool.query(
        `INSERT INTO app.custom_appraisal_workfile_sections (
           assignment_file_id, section_key, section_value, revision
         ) VALUES ($1, $2, $3::jsonb, $4)`,
        [assignmentId, sectionKey, JSON.stringify(section.value), section.revision],
      );
    }

    const auth = { userId: actorUserId, organizations: [{ organizationId, roles: ["appraiser"] }] };
    const authorized = await authorizeUadWorkfileAccess(pool, auth, workfile.id, { write: true });
    const confirmation = authorizeUadAppraiserConfirmation(auth, authorized);
    const receipt = Object.freeze({
      workfileId: authorized.id,
      organizationId: authorized.organization_id,
      actorUserId: confirmation.actorUserId,
      signerRole: confirmation.signerRole,
    });
    const suggestions = await loadUadCompletionSuggestions(pool, workfile.id);
    const selected = suggestions.suggestions.sales_comparison_fields.find((item) => (
      item.field_key === "sales_comparison_summary:1300.0006"
    ));
    assert.ok(selected);
    const result = await applyUadCompletionSuggestions(pool, workfile.id, {
      selected_suggestion_ids: [selected.suggestion_id],
      expected_source_digest_sha256: suggestions.source_completion.source_digest_sha256,
      expected_adapter_version: suggestions.adapter_version,
      expected_revision: 1,
      preserve_existing: true,
      confirmed: true,
    }, actorUserId, receipt);

    assert.equal(result.current_revision, 2);
    assert.equal(result.applied_suggestion_count, 1);
    const saved = await pool.query(
      `SELECT value, source_type, is_appraiser_confirmed
         FROM appraisal.uad_field_values
        WHERE workfile_id = $1
          AND field_context = 'sales_comparison_summary'
          AND uad_uid = '1300.0006'`,
      [workfile.id],
    );
    assert.deepEqual(saved.rows[0], {
      value: 302000,
      source_type: "homenode",
      is_appraiser_confirmed: true,
    });
    const audit = await pool.query(
      `SELECT count(*)::integer AS count, array_agg(actor_user_id::text) AS actors
         FROM appraisal.uad_audit_events
        WHERE workfile_id = $1
          AND event_type = 'uad_completion_suggestions.applied'`,
      [workfile.id],
    );
    assert.equal(audit.rows[0].count, 1);
    assert.deepEqual(audit.rows[0].actors, [actorUserId]);
  } finally {
    try {
      await cleanupIntegrationFixture(pool, accountId, organizationId, actorUserId);
    } finally {
      await pool.end();
    }
  }
});
