import assert from "node:assert/strict";
import test from "node:test";

import {
  createNeighborhoodReviewState, updateNeighborhoodReviewContext,
  startNeighborhoodReviewLoad, receiveNeighborhoodReviewLoad, failNeighborhoodReviewLoad,
  selectNeighborhoodReviewGroup, confirmNeighborhoodReviewGroup,
  beginNeighborhoodReviewApply, finishNeighborhoodReviewApply, buildNeighborhoodReviewView,
} from "../src/features/uad/neighborhoodReviewModel.ts";
import { prepareUadNeighborhoodApply } from "../../server/src/modules/uad/neighborhoodReview.js";
import {
  uadNeighborhoodReviewFixture, acceptedUadNeighborhoodReviewFixture, prepareSyntheticAcceptance,
} from "./fixtures/uadNeighborhoodReviewFixture.mjs";

const clone = value => structuredClone(value);
function loaded(fixture = uadNeighborhoodReviewFixture(), initial = createNeighborhoodReviewState(fixture.context)) {
  const load = startNeighborhoodReviewLoad(initial);
  return receiveNeighborhoodReviewLoad(load.state, load.token, fixture.preview);
}
function confirmed(fixture = uadNeighborhoodReviewFixture(), initial) {
  return confirmNeighborhoodReviewGroup(selectNeighborhoodReviewGroup(loaded(fixture, initial), true), true);
}
function blocked(state) {
  assert.equal(buildNeighborhoodReviewView(state).canApply, false);
  assert.equal(beginNeighborhoodReviewApply(state), null);
}
function started(fixture = uadNeighborhoodReviewFixture()) {
  const begin = beginNeighborhoodReviewApply(confirmed(fixture));
  assert.ok(begin);
  return begin;
}
function otherContext(context) {
  return { ...context, workfileId: "70000000-0000-4000-8000-000000000099", reportFileId: "60000000-0000-4000-8000-000000000099" };
}

test("real backend candidate starts with no selection or confirmation", () => {
  const fixture = uadNeighborhoodReviewFixture();
  const state = loaded(fixture);
  const view = buildNeighborhoodReviewView(state);
  assert.equal(view.selected, false);
  assert.equal(view.confirmed, false);
  assert.equal(view.fields.length, 7);
  assert.ok(view.fields.every(field => field.required && !field.selected));
  blocked(state);
});

test("select and clear operate on every member and explicit confirmation remains separate", () => {
  let state = loaded();
  state = selectNeighborhoodReviewGroup(state, true);
  assert.ok(buildNeighborhoodReviewView(state).fields.every(field => field.selected));
  blocked(state);
  state = confirmNeighborhoodReviewGroup(state, true);
  assert.equal(buildNeighborhoodReviewView(state).canApply, true);
  state = selectNeighborhoodReviewGroup(state, false);
  assert.equal(state.confirmed, false);
  assert.ok(buildNeighborhoodReviewView(state).fields.every(field => !field.selected));
  blocked(state);
});

test("request generated by UI has exact real backend contract parity and no field values", () => {
  const fixture = uadNeighborhoodReviewFixture();
  const begin = started(fixture);
  assert.deepEqual(begin.command.body, fixture.backend.request);
  assert.deepEqual(begin.command.body.selected_suggestion_ids, fixture.backend.candidate.suggestions.map(item => item.id));
  assert.equal(Object.hasOwn(begin.command.body, "values"), false);
  const accepted = prepareSyntheticAcceptance(fixture, begin.command);
  assert.equal(accepted.plan.writes.length, 7);
  assert.equal(accepted.receipt.core_receipt.accepted_editor_revision, 6);
});

test("compatible boundary reuse stays visible and selected beside new fields", () => {
  const fixture = uadNeighborhoodReviewFixture({ reuseKeys: ["market:3000.0008"] });
  assert.equal(fixture.plan.acceptance_manifest.reused.length, 1);
  const view = buildNeighborhoodReviewView(confirmed(fixture));
  assert.equal(view.fields.filter(field => field.state === "reuse").length, 1);
  assert.ok(view.fields.every(field => field.selected));
  const begin = started(fixture);
  assert.equal(begin.command.body.selected_suggestion_ids.length, 7);
  const accepted = prepareSyntheticAcceptance(fixture, begin.command);
  assert.equal(accepted.result.applied_count, 6);
  assert.equal(accepted.result.reused_count, 1);
  const complete = finishNeighborhoodReviewApply(begin.state, begin.token, accepted.result);
  assert.deepEqual(complete.mutation, { workfileId: fixture.context.workfileId, revision: 6 });
});

test("manual boundary is a real whole-group conflict even when displayed text is equal", () => {
  const fixture = uadNeighborhoodReviewFixture({ conflictKeys: ["market:3000.0008"] });
  assert.equal(fixture.plan.status, "conflict");
  const state = confirmed(fixture);
  const view = buildNeighborhoodReviewView(state);
  assert.equal(view.fields.length, 7);
  assert.equal(view.fields.filter(field => field.state === "conflict").length, 1);
  assert.ok(view.fields.every(field => !field.selected));
  assert.match(view.blockers.join(" "), /preserved/);
  blocked(state);
});

test("server-wide blocking issues prevent confirming a seemingly new group", () => {
  const fixture = uadNeighborhoodReviewFixture();
  fixture.preview.blocking_issues.push("The assessment requires source review.");
  const state = confirmed(fixture);
  assert.ok(buildNeighborhoodReviewView(state).blockers.includes("The assessment requires source review."));
  blocked(state);
});

test("verified zero-sales group retains known zero and selects exactly four mapped members", () => {
  const fixture = uadNeighborhoodReviewFixture({ zeroSales: true });
  const begin = started(fixture);
  assert.equal(begin.command.body.selected_suggestion_ids.length, 4);
  const view = buildNeighborhoodReviewView(confirmed(fixture));
  assert.ok(view.fields.some(field => field.rawValue === 0 && field.displayValue === "0"));
  assert.equal(prepareSyntheticAcceptance(fixture, begin.command).plan.writes.length, 4);
});

test("evidence shows full sources, periods, populations, statistics, dependencies and omissions", () => {
  const fixture = uadNeighborhoodReviewFixture({ reuseKeys: ["market:3000.0008"] });
  const view = buildNeighborhoodReviewView(loaded(fixture));
  assert.deepEqual(view.evidence.sources, fixture.preview.candidate.evidence.sources);
  assert.deepEqual(view.evidence.populations, fixture.preview.candidate.evidence.populations);
  assert.deepEqual(view.evidence.statistics, fixture.preview.candidate.evidence.statistics);
  assert.deepEqual(view.evidence.period, fixture.backend.market_context.observation_period);
  assert.equal(view.evidence.effectiveDate, fixture.backend.candidate.group.effective_date);
  assert.equal(view.evidence.dataCutoff, fixture.backend.candidate.group.data_cutoff);
  assert.equal(view.evidence.sources[0].observed_at, fixture.backend.assessment.source_snapshots[0].observed_at);
  for (const item of fixture.preview.candidate.suggestions) {
    const field = view.fields.find(field => field.id === item.id);
    assert.deepEqual(field.evidenceRefs, item.evidence_refs);
    assert.deepEqual(field.dependencyIds, item.dependency_ids);
  }
  assert.deepEqual(view.omissions.map(item => item.code), fixture.preview.candidate.omissions);
  assert.ok(view.omissions.every(item => item.message.length > 0));
});

test("different market-analysis and geographic-neighborhood evidence remain distinct", () => {
  const fixture = uadNeighborhoodReviewFixture();
  fixture.preview.candidate.evidence.market_context.analysis_geometry = { role: "competitive_market", revision: "pockets-a-b",
    geometry_sha256: "a".repeat(64), boundary_description: "Two separate competitive pockets." };
  const view = buildNeighborhoodReviewView(loaded(fixture));
  assert.equal(view.evidence.analysisGeography.value.role, "competitive_market");
  assert.notDeepEqual(view.evidence.geographicNeighborhood.value, view.evidence.analysisGeography.value);
});

test("input and returned view mutations cannot change the accepted review snapshot", () => {
  const fixture = uadNeighborhoodReviewFixture();
  const expected = clone(fixture);
  const state = confirmed(fixture);
  fixture.context.dirty = true;
  fixture.preview.candidate.suggestions[0].value = "Changed after load";
  fixture.preview.candidate.evidence.sources[0].provider = "Changed provider";
  const view = buildNeighborhoodReviewView(state);
  view.evidence.sources[0].provider = "Changed output";
  view.fields[0].evidenceRefs.push("unbound");
  assert.deepEqual(state.context, expected.context);
  assert.deepEqual(state.preview, expected.preview);
  assert.equal(buildNeighborhoodReviewView(state).canApply, true);
});

test("dirty-to-clean at unchanged revision never restores old confirmation", () => {
  const fixture = uadNeighborhoodReviewFixture();
  const original = confirmed(fixture);
  const dirty = updateNeighborhoodReviewContext(original, { ...fixture.context, dirty: true });
  assert.equal(dirty.context.dirty, true);
  blocked(dirty);
  const clean = updateNeighborhoodReviewContext(dirty, fixture.context);
  assert.equal(clean.confirmed, false);
  assert.equal(clean.preview, null);
  blocked(clean);
  const refreshed = loaded(fixture, clean);
  assert.equal(refreshed.confirmed, false);
  blocked(refreshed);
});

test("every target, source-session, revision, permission and signature context change revokes confirmation", () => {
  const fixture = uadNeighborhoodReviewFixture();
  for (const patch of [otherContext(fixture.context), { reportFileId: "different-report" }, { revision: 6 },
    { sessionKey: "replacement-session" }, { specificationRelease: "changed-release" }, { canApply: false },
    { status: "signed" }, { signedAt: "2024-07-01T00:00:00Z" }, { hasSignatures: true }]) {
    const state = updateNeighborhoodReviewContext(confirmed(fixture), { ...fixture.context, ...patch });
    assert.equal(state.confirmed, false);
    assert.equal(state.selected, false);
    assert.equal(state.preview, null);
    blocked(state);
  }
});

test("signed, unknown-signature, read-only and dirty states stay blocked even after a successful load", () => {
  const fixture = uadNeighborhoodReviewFixture();
  for (const patch of [{ dirty: true }, { canApply: false }, { status: "signed" }, { status: "submitted" },
    { status: "exported" }, { status: "cancelled" }, { status: "unknown" }, { signedAt: "signed" },
    { signedAt: undefined }, { hasSignatures: true }, { hasSignatures: null }]) {
    const initial = createNeighborhoodReviewState({ ...fixture.context, ...patch });
    const state = confirmed(fixture, initial);
    blocked(state);
    assert.equal(state.confirmed, false);
  }
});

test("refresh starts revoke selection immediately and failure leaves no old apply path", () => {
  const fixture = uadNeighborhoodReviewFixture();
  const request = startNeighborhoodReviewLoad(confirmed(fixture));
  assert.equal(request.state.preview, null);
  assert.equal(request.state.confirmed, false);
  blocked(request.state);
  const failed = failNeighborhoodReviewLoad(request.state, request.token);
  assert.equal(failed.preview, null);
  assert.equal(failed.needsRefresh, true);
  blocked(confirmNeighborhoodReviewGroup(selectNeighborhoodReviewGroup(failed, true), true));
});

test("newer load wins over an older success or failure at the same workfile revision", () => {
  const fixture = uadNeighborhoodReviewFixture();
  const first = startNeighborhoodReviewLoad(createNeighborhoodReviewState(fixture.context));
  const second = startNeighborhoodReviewLoad(first.state);
  const updated = clone(fixture.preview);
  updated.candidate.evidence.sources[0].revision = "new-source-revision";
  const current = receiveNeighborhoodReviewLoad(second.state, second.token, updated);
  assert.strictEqual(receiveNeighborhoodReviewLoad(current, first.token, fixture.preview), current);
  assert.strictEqual(failNeighborhoodReviewLoad(current, first.token), current);
  assert.equal(current.preview.candidate.evidence.sources[0].revision, "new-source-revision");
});

test("workfile A-to-B-to-A rejects the first A response despite matching identifiers and revision", () => {
  const fixture = uadNeighborhoodReviewFixture();
  const oldA = startNeighborhoodReviewLoad(createNeighborhoodReviewState(fixture.context));
  const atB = updateNeighborhoodReviewContext(oldA.state, otherContext(fixture.context));
  const backA = updateNeighborhoodReviewContext(atB, fixture.context);
  const newA = startNeighborhoodReviewLoad(backA);
  assert.notDeepEqual(newA.token, oldA.token);
  const current = receiveNeighborhoodReviewLoad(newA.state, newA.token, fixture.preview);
  assert.strictEqual(receiveNeighborhoodReviewLoad(current, oldA.token, fixture.preview), current);
  assert.strictEqual(failNeighborhoodReviewLoad(current, oldA.token), current);
});

test("malformed and mismatched previews cannot be selected", () => {
  const mutations = [
    p => { p.preview_version = 2; }, p => { p.candidate.status = "incomplete"; },
    p => { p.binding_digest_sha256 = "0".repeat(64); }, p => { p.candidate.candidate_digest_sha256 = "bad"; },
    p => { p.candidate.attachment.editor_revision++; }, p => { p.candidate.attachment.uad_workfile_id = "another-workfile"; },
    p => { p.candidate.attachment.report_file_id = "another-report"; }, p => { p.candidate.attachment.specification_release = "another-release"; },
    p => { p.members.pop(); }, p => { p.members.push(p.members[0]); }, p => { p.members[0] = { ...p.members[1] }; },
    p => { p.members[0].id = "unknown-member"; }, p => { p.members[0].state = "probably-reuse"; },
    p => { p.candidate.suggestions[0].id = p.candidate.suggestions[1].id; },
    p => { p.candidate.suggestions[0].target_key = p.candidate.suggestions[1].target_key; },
    p => { p.candidate.suggestions[0].target_key = "arbitrary:0000"; },
    p => { p.candidate.suggestions[0].application_group_id = "another-group"; },
    p => { p.candidate.suggestions[0].dependency_ids = ["missing-member"]; },
    p => { p.candidate.suggestions[0].value = Number.NaN; },
    p => { p.candidate.group.application_mode = "partial"; }, p => { p.candidate.group.policy = "best_effort"; },
    p => { delete p.candidate.evidence; }, p => { p.candidate.evidence.sources = null; },
  ];
  for (const mutate of mutations) {
    const fixture = uadNeighborhoodReviewFixture();
    mutate(fixture.preview);
    const state = loaded(fixture);
    assert.equal(state.preview === null, true, mutate.toString());
    assert.equal(state.needsRefresh, true);
    blocked(state);
  }
});

test("an incomplete or absent candidate clears the pending load and cannot confirm", () => {
  const fixture = uadNeighborhoodReviewFixture();
  const begin = startNeighborhoodReviewLoad(createNeighborhoodReviewState(fixture.context));
  const result = receiveNeighborhoodReviewLoad(begin.state, begin.token, null);
  assert.equal(result.pendingLoad, null);
  assert.equal(result.preview, null);
  blocked(result);
});

test("one apply can be pending and a duplicate response cannot announce another mutation", () => {
  const fixture = uadNeighborhoodReviewFixture();
  const begin = started(fixture);
  blocked(confirmNeighborhoodReviewGroup(selectNeighborhoodReviewGroup(begin.state, true), true));
  const accepted = prepareSyntheticAcceptance(fixture, begin.command);
  const complete = finishNeighborhoodReviewApply(begin.state, begin.token, accepted.result);
  assert.deepEqual(complete.mutation, { workfileId: fixture.context.workfileId, revision: 6 });
  assert.equal(complete.state.pendingApply, null);
  assert.equal(complete.state.confirmed, false);
  assert.equal(complete.state.preview, null);
  const replay = finishNeighborhoodReviewApply(complete.state, begin.token, accepted.result);
  assert.strictEqual(replay.state, complete.state);
  assert.equal(replay.mutation, null);
});

test("dirty or revision changes during apply keep the operation pending but never erase current context", () => {
  const fixture = uadNeighborhoodReviewFixture();
  for (const patch of [{ dirty: true }, { revision: 6 }, { hasSignatures: true }, { signedAt: "signed" }]) {
    const begin = started(fixture);
    const context = { ...fixture.context, ...patch };
    const changed = updateNeighborhoodReviewContext(begin.state, context);
    assert.ok(changed.pendingApply);
    blocked(changed);
    const accepted = prepareSyntheticAcceptance(fixture, begin.command);
    const complete = finishNeighborhoodReviewApply(changed, begin.token, accepted.result);
    assert.equal(complete.mutation, null);
    assert.deepEqual(complete.state.context, context);
    assert.equal(complete.state.pendingApply, null);
    assert.equal(complete.state.notice, null);
    assert.equal(complete.state.needsRefresh, true);
  }
});

test("navigation suppresses apply success and failure from the former workfile", () => {
  const fixture = uadNeighborhoodReviewFixture();
  const begin = started(fixture);
  const other = updateNeighborhoodReviewContext(begin.state, otherContext(fixture.context));
  for (const result of [prepareSyntheticAcceptance(fixture, begin.command).result, null]) {
    const complete = finishNeighborhoodReviewApply(other, begin.token, result);
    assert.strictEqual(complete.state, other);
    assert.equal(complete.mutation, null);
  }
});

test("refresh during apply suppresses a late result instead of discarding the newer review", () => {
  const fixture = uadNeighborhoodReviewFixture();
  const begin = started(fixture);
  const refresh = startNeighborhoodReviewLoad(begin.state);
  const current = receiveNeighborhoodReviewLoad(refresh.state, refresh.token, fixture.preview);
  const completed = finishNeighborhoodReviewApply(current, begin.token, prepareSyntheticAcceptance(fixture, begin.command).result);
  assert.equal(completed.mutation, null);
  assert.deepEqual(completed.state.preview, current.preview);
  assert.equal(completed.state.notice, null);
});

test("an obsolete apply token cannot clear a newer apply after an A-B-A navigation", () => {
  const fixture = uadNeighborhoodReviewFixture();
  const first = started(fixture);
  const moved = updateNeighborhoodReviewContext(first.state, otherContext(fixture.context));
  const returned = updateNeighborhoodReviewContext(moved, fixture.context);
  const second = beginNeighborhoodReviewApply(confirmed(fixture, returned));
  assert.ok(second);
  const accepted = prepareSyntheticAcceptance(fixture, first.command);
  for (const result of [accepted.result, null]) {
    const completed = finishNeighborhoodReviewApply(second.state, first.token, result);
    assert.strictEqual(completed.state, second.state);
    assert.equal(completed.mutation, null);
    assert.deepEqual(completed.state.pendingApply.token, second.token);
  }
});

test("prepared plans and mismatched, failed, malformed or impossible save results never announce success", () => {
  const fixture = uadNeighborhoodReviewFixture();
  const begin = started(fixture);
  const accepted = prepareSyntheticAcceptance(fixture, begin.command);
  const badResults = [null, fixture.plan, { ...accepted.result, status: "conflict" },
    { ...accepted.result, status: "ready" }, { ...accepted.result, workfile_id: "other-workfile" },
    { ...accepted.result, candidate_digest_sha256: "0".repeat(64) }, { ...accepted.result, application_group_id: "other-group" },
    { ...accepted.result, current_revision: 7 }, { ...accepted.result, accepted_revision: 7, current_revision: 7 },
    { ...accepted.result, applied_count: 6 }, { ...accepted.result, applied_count: 0 },
    { ...accepted.result, reused_count: 1 }, { ...accepted.result, applied_count: -1 },
    { ...accepted.result, reused_count: 0.5 }, { ...accepted.result, accepted_revision: "6" },
    { ...accepted.result, status: "already_applied", applied_count: 1 },
    { ...accepted.result, status: "already_applied", applied_count: 0, reused_count: 6 },
  ];
  for (const result of badResults) {
    const completed = finishNeighborhoodReviewApply(begin.state, begin.token, result);
    assert.equal(completed.mutation, null, JSON.stringify(result));
    assert.equal(completed.state.notice, null);
    assert.equal(completed.state.needsRefresh, true);
    assert.ok(completed.state.error);
    blocked(completed.state);
  }
});

test("exact real-receipt replay submits all reused IDs and shows original revision with no mutation", () => {
  const fixture = acceptedUadNeighborhoodReviewFixture();
  const state = confirmed(fixture);
  assert.ok(buildNeighborhoodReviewView(state).fields.every(field => field.state === "reuse" && field.selected));
  const begin = beginNeighborhoodReviewApply(state);
  assert.ok(begin);
  const backend = prepareUadNeighborhoodApply({ ...fixture.backend, request: begin.command.body });
  assert.equal(backend.status, "already_applied");
  assert.deepEqual(backend.writes, []);
  const complete = finishNeighborhoodReviewApply(begin.state, begin.token, fixture.result);
  assert.equal(complete.mutation, null);
  assert.match(complete.state.notice, /already saved/i);
  assert.match(complete.state.notice, /no additional changes/i);
  assert.deepEqual(buildNeighborhoodReviewView(complete.state).acceptance, {
    acceptedRevision: fixture.result.accepted_revision, alreadyApplied: true,
    appliedCount: 0, reusedCount: fixture.result.reused_count,
  });
  assert.equal(complete.state.error, null);
});

test("all-new review can receive an exact already-applied retry result without claiming a fresh save", () => {
  const fixture = uadNeighborhoodReviewFixture();
  const begin = started(fixture);
  const accepted = prepareSyntheticAcceptance(fixture, begin.command);
  const result = { ...accepted.result, status: "already_applied", applied_count: 0, reused_count: 7 };
  const complete = finishNeighborhoodReviewApply(begin.state, begin.token, result);
  assert.equal(complete.mutation, null);
  assert.match(complete.state.notice, /already saved/i);
  assert.equal(complete.state.error, null);
});

test("load and apply calls are pure and do not mutate input state, tokens or server objects", () => {
  const fixture = uadNeighborhoodReviewFixture();
  const initial = createNeighborhoodReviewState(fixture.context);
  const initialCopy = clone(initial);
  const fixtureCopy = clone(fixture);
  const load = startNeighborhoodReviewLoad(initial);
  const state = receiveNeighborhoodReviewLoad(load.state, load.token, fixture.preview);
  const stateCopy = clone(state);
  const apply = beginNeighborhoodReviewApply(confirmNeighborhoodReviewGroup(selectNeighborhoodReviewGroup(state, true), true));
  const applyCopy = clone(apply);
  finishNeighborhoodReviewApply(apply.state, apply.token, prepareSyntheticAcceptance(fixture, apply.command).result);
  assert.deepEqual(initial, initialCopy);
  assert.deepEqual(fixture, fixtureCopy);
  assert.deepEqual(state, stateCopy);
  assert.deepEqual(apply, applyCopy);
});

test("saved acceptance metadata is cleared when a new review, target or selection replaces it", () => {
  const fixture = acceptedUadNeighborhoodReviewFixture();
  const begin = started(fixture);
  const complete = finishNeighborhoodReviewApply(begin.state, begin.token, fixture.result).state;
  assert.ok(buildNeighborhoodReviewView(complete).acceptance);
  for (const state of [startNeighborhoodReviewLoad(complete).state,
    updateNeighborhoodReviewContext(complete, { ...fixture.context, dirty: true }),
    selectNeighborhoodReviewGroup(complete, false)]) {
    assert.equal(buildNeighborhoodReviewView(state).acceptance, null);
  }
});

test("refresh during apply also suppresses a stale failure without replacing the newer review", () => {
  const fixture = uadNeighborhoodReviewFixture();
  const begin = started(fixture);
  const refresh = startNeighborhoodReviewLoad(begin.state);
  const current = receiveNeighborhoodReviewLoad(refresh.state, refresh.token, fixture.preview);
  const completed = finishNeighborhoodReviewApply(current, begin.token, null);
  assert.equal(completed.mutation, null);
  assert.deepEqual(completed.state.preview, current.preview);
  assert.equal(completed.state.error, null);
  assert.equal(completed.state.pendingApply, null);
});

test("missing, duplicate or mismatched display evidence cannot be presented as a complete review", () => {
  const mutations = [
    p => { p.candidate.evidence.sources = []; },
    p => { p.candidate.evidence.statistics = []; },
    p => { p.candidate.evidence.populations = []; },
    p => { delete p.candidate.evidence.sources; },
    p => { delete p.candidate.evidence.statistics; },
    p => { delete p.candidate.evidence.populations; },
    p => { p.candidate.evidence.statistics.pop(); },
    p => { p.candidate.evidence.populations.pop(); },
    p => { p.candidate.evidence.sources[0].id = "unrelated-source"; },
    p => { p.candidate.evidence.statistics[0].id = "unrelated-statistic"; },
    p => { p.candidate.evidence.populations[0].id = "unrelated-population"; },
    p => { p.candidate.evidence.sources.push(clone(p.candidate.evidence.sources[0])); },
    p => { p.candidate.evidence.statistics.push(clone(p.candidate.evidence.statistics[0])); },
    p => { p.candidate.evidence.populations.push(clone(p.candidate.evidence.populations[0])); },
    p => { p.candidate.evidence.sources[0] = null; },
    p => { p.candidate.evidence.statistics[0] = "missing-statistic-record"; },
    p => { p.candidate.evidence.populations[0] = 5; },
    p => { p.candidate.group.source_refs = []; },
    p => { p.candidate.group.required_statistic_ids = []; },
    p => { p.candidate.group.population_refs = []; },
    p => { p.candidate.suggestions[0].evidence_refs.push("source:missing-source"); },
    p => { p.candidate.suggestions[0].evidence_refs.push("statistic:missing-statistic"); },
    p => { p.candidate.suggestions[0].evidence_refs.push("population:missing-population"); },
    p => { p.candidate.suggestions[0].evidence_refs.push("unrecognized-evidence-kind"); },
    p => { delete p.candidate.attachment.effective_date; },
    p => { delete p.candidate.attachment.data_cutoff; },
  ];
  for (const mutate of mutations) {
    const fixture = uadNeighborhoodReviewFixture();
    mutate(fixture.preview);
    const state = loaded(fixture);
    assert.equal(state.preview === null, true, mutate.toString());
    assert.equal(state.needsRefresh, true);
    blocked(state);
  }
});

test("four-member positive sales or incorrect zero-sales field sets are incomplete", () => {
  const common = new Set(["market:3000.0008", "market:3000.0010", "market:3000.0009", "market_total_sales:3000.0026"]);
  const positive = uadNeighborhoodReviewFixture();
  positive.preview.candidate.suggestions = positive.preview.candidate.suggestions.filter(item => common.has(item.target_key));
  positive.preview.members = positive.preview.members.filter(member => positive.preview.candidate.suggestions.some(item => item.id === member.id));
  assert.equal(positive.preview.candidate.suggestions.length, 4);
  assert.equal(loaded(positive).preview === null, true, "positive sales require all three price members");

  const zeroWithPrices = uadNeighborhoodReviewFixture();
  zeroWithPrices.preview.candidate.suggestions.find(item => item.target_key === "market_total_sales:3000.0026").value = 0;
  assert.equal(loaded(zeroWithPrices).preview === null, true, "zero sales cannot retain price members");

  const wrongZeroKeys = uadNeighborhoodReviewFixture({ zeroSales: true });
  const months = wrongZeroKeys.preview.candidate.suggestions.find(item => item.target_key === "market:3000.0009");
  months.target_key = "market_total_sales:3000.0029";
  months.value = 330000;
  assert.equal(wrongZeroKeys.preview.candidate.suggestions.length, 4);
  assert.equal(loaded(wrongZeroKeys).preview === null, true, "four members must be the exact zero-sales field set");

  const stringZero = uadNeighborhoodReviewFixture({ zeroSales: true });
  stringZero.preview.candidate.suggestions.find(item => item.target_key === "market_total_sales:3000.0026").value = "0";
  assert.equal(loaded(stringZero).preview === null, true, "a string count is an unsupported scalar shape");
});

test("unknown dirty state cannot be interpreted as a clean editor", () => {
  const fixture = uadNeighborhoodReviewFixture();
  for (const dirty of [undefined, null, "false", 0]) {
    const state = confirmed(fixture, createNeighborhoodReviewState({ ...fixture.context, dirty }));
    blocked(state);
    assert.equal(state.confirmed, false);
  }
});

test("malformed session, target and revision context cannot enable a matching preview", () => {
  const cases = [
    ...[null, undefined, "", "   ", 123, {}, []].map(value => ["sessionKey", value, null]),
    ...[null, undefined, "5", 0, -1, 1.5, Number.NaN, Number.POSITIVE_INFINITY, Number.MAX_SAFE_INTEGER + 1]
      .map(value => ["revision", value, "editor_revision"]),
    ...["workfileId", "reportFileId", "specificationRelease"].flatMap(key =>
      [null, undefined, "", "   ", 123].map(value => [key, value,
        { workfileId: "uad_workfile_id", reportFileId: "report_file_id", specificationRelease: "specification_release" }[key]])),
  ];
  for (const [key, value, attachmentKey] of cases) {
    const fixture = uadNeighborhoodReviewFixture();
    fixture.context[key] = value;
    if (attachmentKey) fixture.preview.candidate.attachment[attachmentKey] = value;
    const state = loaded(fixture);
    assert.equal(state.preview === null, true, `${key}: ${String(value)}`);
    blocked(state);
  }
});

test("duplicate and unresolved dependency IDs cannot produce an atomic review", () => {
  for (const mutate of [
    item => { item.dependency_ids = [item.dependency_ids[0], item.dependency_ids[0]]; },
    item => { item.dependency_ids = ["unresolved-member"]; },
    item => { item.dependency_ids = null; },
    item => { delete item.dependency_ids; },
  ]) {
    const fixture = uadNeighborhoodReviewFixture();
    const item = fixture.preview.candidate.suggestions.find(item => item.dependency_ids.length > 0);
    mutate(item);
    const state = loaded(fixture);
    assert.equal(state.preview === null, true, mutate.toString());
    blocked(state);
  }
});

test("blank manifest IDs and duplicate evidence references are malformed display identities", () => {
  const blank = uadNeighborhoodReviewFixture();
  const oldId = blank.preview.candidate.suggestions[0].id;
  blank.preview.candidate.suggestions[0].id = "   ";
  blank.preview.members.find(item => item.id === oldId).id = "   ";
  for (const item of blank.preview.candidate.suggestions) item.dependency_ids = item.dependency_ids.map(id => id === oldId ? "   " : id);
  assert.equal(loaded(blank).preview === null, true, "whitespace is not a suggestion identity");
  const duplicate = uadNeighborhoodReviewFixture();
  const refs = duplicate.preview.candidate.suggestions[0].evidence_refs;
  refs.push(refs[0]);
  assert.equal(loaded(duplicate).preview === null, true, "duplicate references are unsupported");
});

test("truthy primitive and array placeholders cannot stand in for geographic and period evidence", () => {
  for (const key of ["geographic_neighborhood", "analysis_geometry", "observation_period", "population_ref"]) {
    for (const value of [true, "Evidence unavailable", 123, []]) {
      const fixture = uadNeighborhoodReviewFixture();
      if (key === "geographic_neighborhood") fixture.preview.candidate.evidence[key] = value;
      else fixture.preview.candidate.evidence.market_context[key] = value;
      const state = loaded(fixture);
      assert.equal(state.preview === null, true, `${key}: ${JSON.stringify(value)}`);
      blocked(state);
    }
  }
});

test("selection and confirmation require boolean true rather than truthy event values", () => {
  const fixture = uadNeighborhoodReviewFixture();
  for (const value of ["false", "true", 1, {}, []]) {
    const unselected = selectNeighborhoodReviewGroup(loaded(fixture), value);
    assert.equal(unselected.selected, false);
    blocked(confirmNeighborhoodReviewGroup(unselected, true));
    const selected = selectNeighborhoodReviewGroup(loaded(fixture), true);
    const unconfirmed = confirmNeighborhoodReviewGroup(selected, value);
    assert.equal(unconfirmed.confirmed, false);
    blocked(unconfirmed);
  }
});
