const condition = (key, equals) => ({ key, equals });

const energyFeatureExists = Object.freeze({
  any: [
    condition("energy_green:2600.0005", true),
    condition("energy_green:2600.0004", true),
    condition("energy_green:2600.0003", true),
  ],
});

const disasterMitigationDisplays = Object.freeze({
  all: [
    { key: "disaster_mitigation:3700.0002", present: true },
    { not: { key: "disaster_mitigation:3700.0002", contains: "None" } },
  ],
});

export const UAD_DISASTER_ENERGY_ENTITY_GROUPS = Object.freeze({
  renewable_energy_component: {
    title: "Renewable energy components",
    addLabel: "Add renewable energy component",
    minItems: 1,
    showWhen: condition("energy_green:2600.0005", true),
  },
  green_building_certification: {
    title: "Building certifications",
    addLabel: "Add building certification",
    minItems: 1,
    showWhen: condition("energy_green:2600.0004", true),
  },
  green_efficiency_rating: {
    title: "Green efficiency ratings",
    addLabel: "Add efficiency rating",
    minItems: 1,
    showWhen: condition("energy_green:2600.0003", true),
  },
});

export const UAD_DISASTER_ENERGY_FIELDS = [
  {
    section: "disaster_mitigation",
    group: "Disaster mitigation features",
    contextKey: "disaster_mitigation",
    uid: "3700.0002",
    reportFieldId: "5.000",
    label: "Mitigation features",
    dataType: "multi_enum",
    required: true,
    options: [
      "None",
      "EnclosedSoffits",
      "FireResistantDecking",
      "FireResistantExteriorWalls",
      "FloodVents",
      "FortifiedRoof",
      "FramingAnchorageOrBracing",
      "ImpactResistantGlass",
      "ImpactResistantShingles",
      "NoncombustiblePerimeter",
      "StormShelter",
      "StormShutters",
      "WaterHeaterStrapping",
      "Other",
    ],
  },
  {
    section: "disaster_mitigation",
    group: "Disaster mitigation features",
    contextKey: "disaster_mitigation",
    uid: "3700.0003",
    reportFieldId: "5.000",
    label: "Other mitigation feature",
    dataType: "string",
    maxLength: 33,
    showWhen: { key: "disaster_mitigation:3700.0002", contains: "Other" },
    requiredWhen: { key: "disaster_mitigation:3700.0002", contains: "Other" },
  },
  {
    section: "disaster_mitigation",
    group: "Section commentary",
    contextKey: "disaster_mitigation_commentary",
    uid: "3700.0004",
    reportFieldId: "5.001",
    label: "Disaster mitigation commentary",
    dataType: "text",
    maxLength: 5000,
    showWhen: disasterMitigationDisplays,
    requiredWhen: disasterMitigationDisplays,
  },
  {
    section: "energy_green",
    group: "Known energy and green features",
    contextKey: "energy_green",
    uid: "2600.0005",
    reportFieldId: "6.000",
    label: "Known renewable energy components",
    dataType: "boolean",
    required: true,
  },
  {
    section: "energy_green",
    group: "Known energy and green features",
    contextKey: "energy_green",
    uid: "2600.0004",
    reportFieldId: "6.004",
    label: "Known building certifications",
    dataType: "boolean",
    required: true,
  },
  {
    section: "energy_green",
    group: "Known energy and green features",
    contextKey: "energy_green",
    uid: "2600.0003",
    reportFieldId: "6.010",
    label: "Known efficiency ratings",
    dataType: "boolean",
    required: true,
  },
  {
    section: "energy_green",
    group: "Renewable energy components",
    contextKey: "renewable_energy_component",
    entityType: "renewable_energy_component",
    uid: "2600.0019",
    reportFieldId: "6.001",
    label: "Renewable energy component",
    dataType: "enum",
    required: true,
    options: ["Geothermal", "Solar", "WindTurbine", "Other"],
  },
  {
    section: "energy_green",
    group: "Renewable energy components",
    contextKey: "renewable_energy_component",
    entityType: "renewable_energy_component",
    uid: "2600.0020",
    reportFieldId: "6.001",
    label: "Other renewable energy component",
    dataType: "string",
    maxLength: 60,
    showWhen: condition("renewable_energy_component:2600.0019", "Other"),
    requiredWhen: condition("renewable_energy_component:2600.0019", "Other"),
  },
  {
    section: "energy_green",
    group: "Renewable energy components",
    contextKey: "renewable_energy_component",
    entityType: "renewable_energy_component",
    uid: "2600.0017",
    reportFieldId: "6.002",
    label: "Ownership",
    dataType: "enum",
    options: ["Leased", "Owned", "PowerPurchaseAgreement", "Other"],
  },
  {
    section: "energy_green",
    group: "Renewable energy components",
    contextKey: "renewable_energy_component",
    entityType: "renewable_energy_component",
    uid: "2600.0018",
    reportFieldId: "6.002",
    label: "Other ownership arrangement",
    dataType: "string",
    maxLength: 60,
    showWhen: condition("renewable_energy_component:2600.0017", "Other"),
    requiredWhen: condition("renewable_energy_component:2600.0017", "Other"),
  },
  {
    section: "energy_green",
    group: "Renewable energy components",
    contextKey: "renewable_energy_component",
    entityType: "renewable_energy_component",
    uid: "2600.0016",
    reportFieldId: "6.003",
    label: "Subject to a financing arrangement",
    dataType: "boolean",
    showWhen: condition("renewable_energy_component:2600.0017", "Owned"),
    requiredWhen: condition("renewable_energy_component:2600.0017", "Owned"),
  },
  {
    section: "energy_green",
    group: "Building certifications",
    contextKey: "green_building_certification",
    entityType: "green_building_certification",
    uid: "2600.0006",
    reportFieldId: "6.005",
    label: "Certification organization",
    dataType: "string",
    required: true,
    maxLength: 60,
  },
  {
    section: "energy_green",
    group: "Building certifications",
    contextKey: "green_building_certification",
    entityType: "green_building_certification",
    uid: "2600.0009",
    reportFieldId: "6.006",
    label: "Certification",
    dataType: "string",
    required: true,
    maxLength: 30,
  },
  {
    section: "energy_green",
    group: "Building certifications",
    contextKey: "green_building_certification",
    entityType: "green_building_certification",
    uid: "2600.0007",
    reportFieldId: "6.007",
    label: "Year awarded",
    dataType: "year",
    maxLength: 4,
  },
  {
    section: "energy_green",
    group: "Building certifications",
    contextKey: "green_building_certification",
    entityType: "green_building_certification",
    uid: "2600.0010",
    reportFieldId: "6.008",
    label: "Certification version",
    dataType: "string",
    maxLength: 20,
  },
  {
    section: "energy_green",
    group: "Building certifications",
    contextKey: "green_building_certification",
    entityType: "green_building_certification",
    uid: "2600.0008",
    reportFieldId: "6.009",
    label: "Certification rating",
    dataType: "string",
    maxLength: 10,
  },
  {
    section: "energy_green",
    group: "Green efficiency ratings",
    contextKey: "green_efficiency_rating",
    entityType: "green_efficiency_rating",
    uid: "2600.0013",
    reportFieldId: "6.011",
    label: "Rating organization",
    dataType: "string",
    required: true,
    maxLength: 60,
  },
  {
    section: "energy_green",
    group: "Green efficiency ratings",
    contextKey: "green_efficiency_rating",
    entityType: "green_efficiency_rating",
    uid: "2600.0012",
    reportFieldId: "6.012",
    label: "Efficiency rating",
    dataType: "string",
    required: true,
    maxLength: 30,
  },
  {
    section: "energy_green",
    group: "Green efficiency ratings",
    contextKey: "green_efficiency_rating",
    entityType: "green_efficiency_rating",
    uid: "2600.0014",
    reportFieldId: "6.013",
    label: "Rating score",
    dataType: "string",
    required: true,
    maxLength: 10,
  },
  {
    section: "energy_green",
    group: "Impact to value and marketability",
    contextKey: "energy_green",
    uid: "2600.0027",
    reportFieldId: "6.014",
    label: "Impact to value or marketability",
    dataType: "enum",
    options: ["Adverse", "Beneficial", "Neutral"],
    showWhen: energyFeatureExists,
    requiredWhen: energyFeatureExists,
  },
  {
    section: "energy_green",
    group: "Impact to value and marketability",
    contextKey: "energy_green",
    uid: "2600.0026",
    reportFieldId: "6.015",
    label: "Impact description",
    dataType: "text",
    maxLength: 2500,
    showWhen: energyFeatureExists,
    requiredWhen: {
      all: [energyFeatureExists, condition("energy_green:2600.0027", "Adverse")],
    },
  },
  {
    section: "energy_green",
    group: "Section commentary",
    contextKey: "energy_green_commentary",
    uid: "2600.0040",
    reportFieldId: "6.016",
    label: "Energy efficient and green features commentary",
    dataType: "text",
    maxLength: 5000,
    showWhen: energyFeatureExists,
  },
];

export { disasterMitigationDisplays, energyFeatureExists };
