-- Additive Custom-only reported observations. No rewritten evidence or v1 hashes.
-- Existing v1 predicates are retained verbatim for the four legacy units.
-- No provider coverage, economic-property equivalence or historical support is
-- established by these storage checks. The existing repository verifies hashes.

CREATE OR REPLACE FUNCTION app.neighborhood_observation_count(value jsonb)
RETURNS boolean LANGUAGE sql IMMUTABLE PARALLEL SAFE SET search_path = pg_catalog AS $$
  SELECT CASE WHEN value IS NOT DISTINCT FROM 'null'::jsonb THEN true
    WHEN jsonb_typeof(value) = 'number' AND (value #>> '{}') ~ '^(0|[1-9][0-9]{0,15})$'
    THEN (value #>> '{}')::numeric <= 9007199254740991 ELSE false END
$$;

-- Only CHECKs referencing changed units/property-counter columns need a new
-- branch. Catalog expression reuse preserves SQL NULL behavior and the complete
-- original predicate, rather than guessing autogenerated constraint names.
DO $$
DECLARE constraint_row record; affected_count integer;
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid='app.neighborhood_assessment_populations'::regclass
    AND conname='neighborhood_observation_population_v2_check') THEN
  SELECT count(*) INTO affected_count FROM pg_constraint c
    WHERE c.conrelid='app.neighborhood_assessment_populations'::regclass AND c.contype='c'
      AND EXISTS (SELECT 1 FROM pg_attribute a WHERE a.attrelid=c.conrelid
        AND a.attnum=ANY(c.conkey) AND a.attname IN ('member_unit','unique_property_count','property_link_count'));
  -- The released table has exactly eleven affected predicates. Refuse an
  -- unexpected schema instead of relaxing additional, unrelated local checks.
  IF affected_count <> 11 THEN RAISE EXCEPTION 'neighborhood_observation_constraint_prerequisite_mismatch'; END IF;
  FOR constraint_row IN
    SELECT c.conname, pg_get_expr(c.conbin,c.conrelid) AS expression
      FROM pg_constraint c
      WHERE c.conrelid='app.neighborhood_assessment_populations'::regclass AND c.contype='c'
        AND EXISTS (SELECT 1 FROM pg_attribute a WHERE a.attrelid=c.conrelid
          AND a.attnum=ANY(c.conkey) AND a.attname IN ('member_unit','unique_property_count','property_link_count'))
  LOOP
    EXECUTE format('ALTER TABLE app.neighborhood_assessment_populations DROP CONSTRAINT %I', constraint_row.conname);
    EXECUTE format('ALTER TABLE app.neighborhood_assessment_populations ADD CONSTRAINT %I CHECK (member_unit IN (''account'',''source_record'') OR (%s))',
      constraint_row.conname,constraint_row.expression);
  END LOOP;

ALTER TABLE app.neighborhood_assessment_populations
  ADD CONSTRAINT neighborhood_observation_population_v2_check CHECK (
    member_unit NOT IN ('account','source_record') OR (
      unique_property_count IS NULL AND property_link_count IS NULL
      AND NOT (population ?| ARRAY['unique_property_count','property_link_count'])
      AND population->>'member_unit' IS NOT DISTINCT FROM member_unit
      AND ((member_unit='account' AND population->>'kind'='account_observations')
        OR (member_unit='source_record' AND population->>'kind'='source_record_observations'))
      AND population->>'completeness_basis'='complete_retained_roster'
      AND population->>'provider_coverage'='not_established'
      AND app.neighborhood_observation_count(population->'unique_account_count')
      AND app.neighborhood_observation_count(population->'account_link_count')
      AND (completeness <> 'complete' OR (member_count IS NOT NULL AND member_set_sha256 IS NOT NULL
        AND population->'unique_account_count' <> 'null'::jsonb AND population->'account_link_count' <> 'null'::jsonb))
      AND CASE WHEN population->'unique_account_count' <> 'null'::jsonb AND population->'account_link_count' <> 'null'::jsonb
        AND app.neighborhood_observation_count(population->'unique_account_count')
        AND app.neighborhood_observation_count(population->'account_link_count')
        THEN (population->>'unique_account_count')::numeric <= (population->>'account_link_count')::numeric ELSE true END
      AND CASE WHEN member_unit='account' THEN
        (population->'unique_account_count' = 'null'::jsonb OR member_count IS NULL
          OR population->'unique_account_count'=to_jsonb(member_count))
        AND (population->'account_link_count' = 'null'::jsonb OR member_count IS NULL
          OR population->'account_link_count'=to_jsonb(member_count))
        WHEN member_count IS NOT NULL AND population->'account_link_count' <> 'null'::jsonb
          AND app.neighborhood_observation_count(population->'account_link_count')
        THEN (population->>'account_link_count')::numeric BETWEEN member_count AND least(1000::numeric*member_count,250000::numeric)
        ELSE true END
    ) IS TRUE
  );
  END IF;
END $$;

CREATE OR REPLACE FUNCTION app.neighborhood_valid_member_accounts(ids text[], unit text)
RETURNS boolean LANGUAGE sql IMMUTABLE PARALLEL SAFE SET search_path = pg_catalog AS $$
  SELECT CASE WHEN ids IS NULL OR array_ndims(ids) IS DISTINCT FROM 1 OR array_lower(ids, 1) <> 1
    OR cardinality(ids) NOT BETWEEN 1 AND 1000
    OR (unit NOT IN ('canonical_transaction','source_record') AND cardinality(ids) <> 1)
  THEN false ELSE (
    SELECT count(*) = count(DISTINCT account_id) AND bool_and(account_id IS NOT NULL
      AND account_id = btrim(account_id) AND char_length(account_id) BETWEEN 1 AND 100
      AND account_id !~ '[[:cntrl:]]') FROM unnest(ids) AS accounts(account_id)
  ) END
$$;

-- Replace only the affected bodies; all existing trigger registrations, source
-- scope checks, publication immutability, manifests and target locks remain.
CREATE OR REPLACE FUNCTION app.neighborhood_guard_revision_child()
RETURNS trigger LANGUAGE plpgsql SET search_path = pg_catalog, app AS $$
DECLARE parent_status text; parent_assessment jsonb; head app.neighborhood_assessments%ROWTYPE; snapshot_scope jsonb;
BEGIN
  IF TG_OP = 'UPDATE' AND ROW(NEW.assessment_id, NEW.revision) IS DISTINCT FROM ROW(OLD.assessment_id, OLD.revision) THEN
    RAISE EXCEPTION 'neighborhood_child_revision_immutable';
  END IF;
  IF TG_OP = 'DELETE' THEN
    SELECT publication_status, assessment INTO parent_status, parent_assessment FROM app.neighborhood_assessment_revisions
      WHERE assessment_id = OLD.assessment_id AND revision = OLD.revision FOR SHARE;
  ELSE
    SELECT publication_status, assessment INTO parent_status, parent_assessment FROM app.neighborhood_assessment_revisions
      WHERE assessment_id = NEW.assessment_id AND revision = NEW.revision FOR SHARE;
  END IF;
  IF parent_status IS DISTINCT FROM 'staging' THEN RAISE EXCEPTION 'neighborhood_published_child_immutable'; END IF;
  -- V2-only observation units cannot be smuggled under a legacy revision.
  IF TG_OP <> 'DELETE' AND TG_TABLE_NAME IN ('neighborhood_assessment_populations', 'neighborhood_assessment_members') THEN
    IF (parent_assessment->'contract_version' = '2'::jsonb) IS DISTINCT FROM
        (NEW.member_unit IN ('account', 'source_record')) THEN
      RAISE EXCEPTION 'neighborhood_member_contract_version_mismatch';
    END IF;
    IF TG_TABLE_NAME = 'neighborhood_assessment_members' THEN
      IF NEW.member_unit = 'account' AND NEW.account_ids IS DISTINCT FROM ARRAY[NEW.member_id] THEN
        RAISE EXCEPTION 'neighborhood_account_member_identity_mismatch';
      END IF;
    END IF;
  END IF;
  IF TG_OP <> 'DELETE' AND TG_TABLE_NAME = 'neighborhood_assessment_sources' THEN
    SELECT * INTO STRICT head FROM app.neighborhood_assessments WHERE id = NEW.assessment_id;
    snapshot_scope := NEW.source_snapshot->'scope';
    IF (NEW.source_snapshot->>'visibility' = 'public' AND snapshot_scope IS DISTINCT FROM 'null'::jsonb)
      OR (NEW.source_snapshot->>'visibility' IN ('organization', 'assignment')
        AND snapshot_scope->>'organization_id' IS DISTINCT FROM head.organization_id::text)
      OR (NEW.source_snapshot->>'visibility' = 'assignment' AND snapshot_scope IS DISTINCT FROM jsonb_build_object(
        'organization_id', head.organization_id, 'appraisal_case_id', head.appraisal_case_id,
        'subject_snapshot_id', head.subject_snapshot_id, 'account_id', head.account_id)) THEN
      RAISE EXCEPTION 'neighborhood_private_source_scope_mismatch';
    END IF;
  END IF;
  IF TG_OP = 'DELETE' THEN RETURN OLD; END IF;
  RETURN NEW;
END $$;

CREATE OR REPLACE FUNCTION app.neighborhood_guard_revision()
RETURNS trigger LANGUAGE plpgsql SET search_path = pg_catalog, app AS $$
DECLARE head app.neighborhood_assessments%ROWTYPE; actual jsonb; expected jsonb; population_row record;
  members bigint; links bigint; properties bigint;
BEGIN
  IF TG_OP = 'DELETE' THEN
    IF OLD.publication_status = 'published' THEN RAISE EXCEPTION 'neighborhood_published_revision_immutable'; END IF;
    RETURN OLD;
  END IF;
  IF TG_OP = 'INSERT' AND (NEW.publication_status <> 'staging' OR NEW.published_at IS NOT NULL) THEN
    RAISE EXCEPTION 'neighborhood_revision_must_stage';
  END IF;
  IF TG_OP = 'UPDATE' AND (OLD.publication_status <> 'staging' OR NEW.publication_status <> 'published'
    OR (to_jsonb(NEW) - 'publication_status' - 'published_at') IS DISTINCT FROM
       (to_jsonb(OLD) - 'publication_status' - 'published_at')) THEN
    RAISE EXCEPTION 'neighborhood_revision_immutable';
  END IF;
  IF (NEW.assessment->'contract_version' IN ('1'::jsonb, '2'::jsonb)) IS NOT TRUE THEN
    RAISE EXCEPTION 'neighborhood_contract_version_unsupported';
  END IF;
  IF NEW.assessment->'contract_version' = '2'::jsonb AND (
    NEW.assessment#>>'{methodology,version}' IS DISTINCT FROM 'reported-observations-v2'
    OR NEW.assessment#>>'{methodology,geometry_version}' IS DISTINCT FROM 'appraiser-defined-observation-boundary-v1'
    OR NEW.assessment#>>'{methodology,configuration,profile_id}' IS DISTINCT FROM 'custom-reported-observations-v2'
    OR NEW.assessment#>'{methodology,configuration,profile_revision}' IS DISTINCT FROM '1'::jsonb
    OR NEW.assessment#>>'{methodology,configuration,report_basis}' IS DISTINCT FROM 'reported_observations_not_verified_market_facts'
  ) THEN RAISE EXCEPTION 'neighborhood_observation_profile_mismatch'; END IF;
  SELECT * INTO STRICT head FROM app.neighborhood_assessments WHERE id = NEW.assessment_id FOR SHARE;
  IF NEW.assessment->>'id' IS DISTINCT FROM NEW.assessment_id::text
    OR NEW.assessment->'revision' IS DISTINCT FROM to_jsonb(NEW.revision)
    OR NEW.assessment->>'input_signature_sha256' IS DISTINCT FROM NEW.input_signature_sha256
    OR NEW.assessment->>'evidence_digest_sha256' IS DISTINCT FROM NEW.evidence_digest_sha256
    OR NEW.assessment->'scope' IS DISTINCT FROM jsonb_build_object('organization_id', head.organization_id,
      'appraisal_case_id', head.appraisal_case_id, 'subject_snapshot_id', head.subject_snapshot_id, 'account_id', head.account_id) THEN
    RAISE EXCEPTION 'neighborhood_revision_identity_mismatch';
  END IF;
  IF NEW.assessment->>'effective_date' IS NULL OR NEW.assessment->>'data_cutoff' IS NULL
    OR (NEW.assessment->>'data_cutoff')::date > (NEW.assessment->>'effective_date')::date THEN
    RAISE EXCEPTION 'neighborhood_revision_date_mismatch';
  END IF;
  PERFORM app.neighborhood_assert_scope(head.organization_id, head.appraisal_case_id, head.subject_snapshot_id,
    head.account_id, (NEW.assessment->>'effective_date')::date);
  IF TG_OP = 'INSERT' THEN RETURN NEW; END IF;

  SELECT COALESCE(jsonb_agg(p.population ORDER BY p.population_id), '[]'::jsonb) INTO actual
    FROM app.neighborhood_assessment_populations p WHERE p.assessment_id = NEW.assessment_id AND p.revision = NEW.revision;
  SELECT COALESCE(jsonb_agg(value ORDER BY value->>'id'), '[]'::jsonb) INTO expected
    FROM jsonb_array_elements(NEW.assessment->'populations');
  IF actual IS DISTINCT FROM expected THEN RAISE EXCEPTION 'neighborhood_population_manifest_mismatch'; END IF;
  SELECT COALESCE(jsonb_agg(s.source_snapshot ORDER BY s.source_id), '[]'::jsonb) INTO actual
    FROM app.neighborhood_assessment_sources s WHERE s.assessment_id = NEW.assessment_id AND s.revision = NEW.revision;
  SELECT COALESCE(jsonb_agg(value ORDER BY value->>'id'), '[]'::jsonb) INTO expected
    FROM jsonb_array_elements(NEW.assessment->'source_snapshots');
  IF actual IS DISTINCT FROM expected THEN RAISE EXCEPTION 'neighborhood_source_manifest_mismatch'; END IF;
  IF EXISTS (SELECT 1 FROM jsonb_path_query(NEW.assessment, '$.**.source_refs[*]') AS refs(value)
    WHERE jsonb_typeof(value) <> 'string' OR NOT EXISTS (SELECT 1 FROM app.neighborhood_assessment_sources s
      WHERE s.assessment_id = NEW.assessment_id AND s.revision = NEW.revision AND s.source_id = value #>> '{}')) THEN
    RAISE EXCEPTION 'neighborhood_source_reference_missing';
  END IF;
  FOR population_row IN SELECT * FROM app.neighborhood_assessment_populations
    WHERE assessment_id = NEW.assessment_id AND revision = NEW.revision LOOP
    SELECT count(*), COALESCE(sum(cardinality(account_ids)), 0) INTO members, links
      FROM app.neighborhood_assessment_members WHERE assessment_id = NEW.assessment_id AND revision = NEW.revision
        AND population_id = population_row.population_id;
    SELECT count(DISTINCT account_id) INTO properties FROM app.neighborhood_assessment_members m
      CROSS JOIN LATERAL unnest(m.account_ids) accounts(account_id)
      WHERE m.assessment_id = NEW.assessment_id AND m.revision = NEW.revision AND m.population_id = population_row.population_id;
    IF (population_row.member_count IS NOT NULL AND population_row.member_count <> members)
      OR (population_row.property_link_count IS NOT NULL AND population_row.property_link_count <> links)
      OR (population_row.unique_property_count IS NOT NULL AND population_row.unique_property_count <> properties) THEN
      RAISE EXCEPTION 'neighborhood_exact_member_counts_mismatch:%', population_row.population_id;
    END IF;
    IF NEW.assessment->'contract_version' = '2'::jsonb THEN
      IF population_row.member_unit NOT IN ('account', 'source_record')
        OR population_row.unique_property_count IS NOT NULL OR population_row.property_link_count IS NOT NULL
        OR (population_row.population->'unique_account_count' <> 'null'::jsonb
          AND (population_row.population->>'unique_account_count')::bigint IS DISTINCT FROM properties)
        OR (population_row.population->'account_link_count' <> 'null'::jsonb
          AND (population_row.population->>'account_link_count')::bigint IS DISTINCT FROM links) THEN
        RAISE EXCEPTION 'neighborhood_exact_account_counts_mismatch:%', population_row.population_id;
      END IF;
    ELSIF population_row.member_unit IN ('account', 'source_record') THEN
      RAISE EXCEPTION 'neighborhood_member_contract_version_mismatch';
    END IF;
  END LOOP;
  -- Contract/member hashes are recomputed by the pure repository validators;
  -- jsonb::text is not the JS canonicalization and a SHA is not authorization.
  NEW.published_at := clock_timestamp();
  RETURN NEW;
END $$;

CREATE OR REPLACE FUNCTION app.neighborhood_guard_attachment()
RETURNS trigger LANGUAGE plpgsql SET search_path = pg_catalog, app AS $$
DECLARE head app.neighborhood_assessments%ROWTYPE; report app.report_files%ROWTYPE;
  revision_row app.neighborhood_assessment_revisions%ROWTYPE; target_organization uuid; target_account text;
  anchor app.neighborhood_assessment_attachment_anchors%ROWTYPE;
BEGIN
  IF TG_OP <> 'INSERT' THEN RAISE EXCEPTION 'neighborhood_attachment_immutable'; END IF;
  SELECT * INTO STRICT head FROM app.neighborhood_assessments WHERE id = NEW.assessment_id FOR SHARE;
  SELECT * INTO STRICT revision_row FROM app.neighborhood_assessment_revisions
    WHERE assessment_id = NEW.assessment_id AND revision = NEW.assessment_revision FOR SHARE;
  IF revision_row.assessment->'contract_version' = '2'::jsonb AND NEW.workflow_type <> 'custom_appraisal' THEN
    RAISE EXCEPTION 'neighborhood_observation_custom_only';
  END IF;
  PERFORM app.neighborhood_assert_scope(head.organization_id, head.appraisal_case_id, head.subject_snapshot_id,
    head.account_id, (revision_row.assessment->>'effective_date')::date);
  SELECT * INTO STRICT report FROM app.report_files WHERE id = NEW.report_file_id FOR SHARE;
  IF revision_row.publication_status <> 'published' OR NEW.organization_id IS DISTINCT FROM head.organization_id
    OR report.organization_id IS DISTINCT FROM head.organization_id OR report.account_id IS DISTINCT FROM head.account_id
    OR report.appraisal_case_id IS DISTINCT FROM head.appraisal_case_id OR report.subject_snapshot_id IS DISTINCT FROM head.subject_snapshot_id
    OR ROW(report.workflow_type, report.custom_assignment_file_id, report.uad_workfile_id)
      IS DISTINCT FROM ROW(NEW.workflow_type, NEW.custom_assignment_file_id, NEW.uad_workfile_id) THEN
    RAISE EXCEPTION 'neighborhood_attachment_target_mismatch';
  END IF;
  IF NEW.workflow_type = 'custom_appraisal' THEN
    SELECT organization_id, account_id INTO STRICT target_organization, target_account FROM app.assignment_files
      WHERE id = NEW.custom_assignment_file_id FOR SHARE;
  ELSE
    SELECT organization_id, account_id INTO STRICT target_organization, target_account FROM appraisal.uad_workfiles
      WHERE id = NEW.uad_workfile_id FOR SHARE;
  END IF;
  IF target_organization IS DISTINCT FROM head.organization_id OR target_account IS DISTINCT FROM head.account_id THEN
    RAISE EXCEPTION 'neighborhood_attachment_target_scope_mismatch';
  END IF;
  IF NOT (NEW.attachment @> jsonb_build_object('attachment_id', NEW.attachment_id, 'attachment_revision', NEW.attachment_revision,
    'assessment_id', NEW.assessment_id, 'assessment_revision', NEW.assessment_revision, 'report_file_id', NEW.report_file_id,
    'workflow_type', NEW.workflow_type, 'custom_assignment_file_id', NEW.custom_assignment_file_id, 'uad_workfile_id', NEW.uad_workfile_id,
    'application_identity_sha256', NEW.application_identity_sha256, 'binding_digest_sha256', NEW.binding_digest_sha256,
    'scope', revision_row.assessment->'scope', 'effective_date', revision_row.assessment->'effective_date',
    'data_cutoff', revision_row.assessment->'data_cutoff', 'evidence_digest_sha256', revision_row.evidence_digest_sha256)) THEN
    RAISE EXCEPTION 'neighborhood_attachment_manifest_mismatch';
  END IF;
  -- The PK serializes even concurrent first inserts for different revisions.
  -- Under READ COMMITTED the following command sees the winning committed row;
  -- stricter isolation may raise a serialization conflict, never split identity.
  INSERT INTO app.neighborhood_assessment_attachment_anchors
    (attachment_id,organization_id,report_file_id,workflow_type,custom_assignment_file_id,uad_workfile_id,
     account_id,appraisal_case_id,subject_snapshot_id)
    VALUES (NEW.attachment_id,NEW.organization_id,NEW.report_file_id,NEW.workflow_type,NEW.custom_assignment_file_id,NEW.uad_workfile_id,
      head.account_id,head.appraisal_case_id,head.subject_snapshot_id)
    ON CONFLICT (attachment_id) DO NOTHING;
  SELECT * INTO STRICT anchor FROM app.neighborhood_assessment_attachment_anchors WHERE attachment_id = NEW.attachment_id FOR SHARE;
  IF ROW(anchor.organization_id,anchor.report_file_id,anchor.workflow_type,anchor.custom_assignment_file_id,anchor.uad_workfile_id,
      anchor.account_id,anchor.appraisal_case_id,anchor.subject_snapshot_id)
    IS DISTINCT FROM ROW(NEW.organization_id,NEW.report_file_id,NEW.workflow_type,NEW.custom_assignment_file_id,NEW.uad_workfile_id,
      head.account_id,head.appraisal_case_id,head.subject_snapshot_id) THEN
    RAISE EXCEPTION 'neighborhood_attachment_stable_identity_mismatch';
  END IF;
  RETURN NEW;
END $$;
