import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const serverRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const outputPath = join(serverRoot, "src", "modules", "uad", "publicErrorCodes.generated.js");
const sourcePaths = [
  join(serverRoot, "src", "modules", "uad"),
  join(serverRoot, "src", "modules", "delivery"),
  join(serverRoot, "src", "services", "assignmentDocuments.js"),
  join(serverRoot, "src", "services", "documentOcr.js"),
];
const staticCodeShape = /^[a-z][a-z0-9_]{0,95}$/;
const relevantCode = /^(?:uad_|invalid_|document_|assignment_document_|delivery_)/;
const relevantSuffix = /(?:not_found|not_configured|_conflict|_status_locked|_access_denied)$/;
const literal = /(["'`])([a-z][a-z0-9_]{0,95})\1/g;

function sourceFiles(path) {
  if (path.endsWith(".js")) return [path];
  return readdirSync(path, { withFileTypes: true }).flatMap((entry) => {
    const child = join(path, entry.name);
    return entry.isDirectory() ? sourceFiles(child) : entry.name.endsWith(".js") ? [child] : [];
  });
}

function dynamicCodes() {
  const codes = new Set([
    "uad_compliance_token_failed",
    "uad_xml_attribute_value_required",
    "uad_xml_mapping_missing",
    "uad_xml_mapping_path_invalid",
    "uad_xml_entity_missing",
    "uad_xml_duplicate_data_point",
    "uad_xml_signer_name_missing",
    "uad_xml_signer_license_missing",
    "uad_xml_signer_execution_date_missing",
  ]);
  for (const operation of ["upload", "verification", "delete", "download"]) {
    for (const suffix of ["timeout", "network_error", "redirect_forbidden", "failed"]) {
      codes.add(`uad_object_${operation}_${suffix}`);
    }
  }
  for (const provider of ["fannie", "freddie"]) {
    codes.add(`uad_compliance_${provider}_not_configured`);
  }
  for (const artifact of ["pdf", "xml", "asset"]) {
    for (const suffix of ["file_path_mismatch", "size_mismatch", "checksum_mismatch"]) {
      codes.add(`uad_package_${artifact}_${suffix}`);
    }
  }
  for (const reason of [
    "payload", "body_type", "byte_size", "content_type", "content_type_mismatch",
    "image_dimensions", "json", "json_bytes", "json_complexity", "pdf_active_content",
    "pdf_annotation_count", "pdf_page_count", "pdf_structure",
  ]) codes.add(`invalid_uad_asset_${reason}`);
  return codes;
}

export function renderUadPublicErrorCodes() {
  const codes = dynamicCodes();
  for (const root of sourcePaths) {
    for (const path of sourceFiles(root)) {
      if (path === outputPath) continue;
      const source = readFileSync(path, "utf8");
      for (const match of source.matchAll(literal)) {
        const code = match[2];
        if (staticCodeShape.test(code) && (relevantCode.test(code) || relevantSuffix.test(code))) {
          codes.add(code);
        }
      }
    }
  }
  return [
    "// Generated by scripts/generateUadPublicErrorCodes.js. Do not edit by hand.",
    "// Only source-known machine codes may cross the shared UAD API boundary.",
    "export const PUBLIC_UAD_ERROR_CODES = new Set([",
    ...[...codes].sort().map((code) => `  ${JSON.stringify(code)},`),
    "]);",
    "",
  ].join("\n");
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const rendered = renderUadPublicErrorCodes();
  if (process.argv.includes("--write")) {
    writeFileSync(outputPath, rendered);
  } else if (process.argv.includes("--check")) {
    if (readFileSync(outputPath, "utf8").replace(/\r\n/g, "\n") !== rendered) {
      throw new Error("uad_public_error_catalog_stale");
    }
  } else {
    throw new Error("Specify --write or --check");
  }
}
